POST /user/xlsx (엑셀파일 업로드를 통해, 유저를 DB에 등록하기)
kugods-Homepage/kugods-server pull request #10
Opened 2022-11-19 12:17 UTC by woog2roid

## Type
PR 종류를 확인해 주세요.
- [ ] Improvement
- [x] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 어떤 목적의 작업 인가요?
엑셀파일 업로드를 통해, 유저 정보를 서버 DB에 등록하는 자동화 작업

## Why
- 어떤 이유로 작업 하셨나요?
위와 같으며, 자세한 내용은 slack 확인

## Related issue
- 관련된 Ticket을 첨부해 주세요.
#3

## Additional context
- 추가로 알리고 싶으신 내용이 있으신가요?
1. controller의 File관련 내용이 길다고 하면, 빼서 코드를 깔끔히 만들 수 있습니다.
2. service 부분의 코드 추상화 레벨이 상당히 낮은데, 메서드로 깔끔히 할 수는 있으나, 필요성을 잘... 느끼진 못했습니다.
3. DAO관련해서 validation 부족한 부분 있으면 말씀 부탁드립니다.

피드백 부탁드립니다!!

## Checklist
- Merge 나 Deploy 시 확인이 필요한 부분이 있다면 적어주세요.

2022-11-20 04:28 UTC, worjs requested changes
고생하셨습니다!

몇가지만 더 제안드리면,
1. 만약 이미 등록된 유저를 사용자가 또 등록하려고 하면 어떻게 하면 좋을까요? 기존에 있는 정보는 놔두고 나머지만 추가하는 방법도 있을거고, 그건 안된다고 409를 내려주는 방법도 있겠네요.
2. 전체적으로 함수 또는 메소드들에 리턴타입을 명시하는 편을 제안드립니다. 코드 파악하는데 도움이 됩니다! 리턴이 없어도 Promise<void> 혹은 void 이런식으로 해두시면 되겠습니다.

일단 한번 확인해주시고, 이후에 좀더 이야기하시죠!

2022-11-20 04:28 UTC, worjs commented on src/main.ts
> +  app.useGlobalFilters(new HttpExceptionFilter());
nest에서 기본적인건 제공하고 있는데 새로 만드신 이유가 있나요?

2022-11-20 04:28 UTC, worjs commented on src/user/user.controller.ts
> +            new HttpException(
요부분도 요정도 유즈케이스면
`new BadRequestException('.xlsx파일을 업로드해주세요.')`
이렇게 사용하면 될거예요

2022-11-20 04:28 UTC, worjs commented on src/user/user.repository.ts
> +    await this.prisma.user
지금 구조에서는 유저 입장에서 이 api의 요청으로 일부의 데이터만 db에 반영되는 경우가 발생할 수 있습니다.
createMany라고, 여러개의 행을 batch로 insert하는 기능을 제공하는데, 하나의 transaction으로 처리되므로 위와 같은 경우를 막을 수 있습니다.

2022-11-20 04:28 UTC, worjs commented on src/user/user.repository.ts
> +      .catch((err) => {
이렇게 에러를 처리하면 사용자에게 db쿼리가 잘못됨 => 요청한 api가 제대로 수행되지 않았다 라는 정보를 주지 못하게됩니다.
사실 이것보다는 사전에 에러가 날만한 부분을 최대한 validation을 진행한 뒤에 쿼리를 날리도록 설계하는게 좋습니다.
현재 경우에서는 
1. studentId의 unique check
2. 각 데이터의 타입 체크

정도가 있겠네요.

2022-11-20 04:28 UTC, worjs commented on src/user/user.service.ts
> +      else if (xlsxPosition === '주니어') xlsxEntrollDao.setPosition('JUNIOR');
만약에 오타로 인해서, 다른 문자열이 들어왔다면 어떻게 해야할까요?

2022-11-20 04:28 UTC, worjs commented on src/user/dao/xlsx-enroll.dao.ts
> +  public position: 'LEAD' | 'CORE' | 'MEMBER' | 'JUNIOR';
Prisma의 장점중에 하나는 이런거 타입 다 만들어준다는 점입니다!
UserStatus라는 enum type을 가져와서 쓰시면 되겠습니다.
@prisma/client에서 가져올 수 있습니다.

2022-11-20 04:28 UTC, worjs commented on src/user/dao/xlsx-enroll.dao.ts
> +  public name: string;
validator는 저도 좀더 찾아봤는데, 단순히 new로 생성하면 constructor단계에서 실행된다거나 그런게 아니라, validate라는 함수를 통해서 진행할 수 있는 것 같습니다. 다만 그렇게 수행하면 기존처럼 global pipe에 등록해서 사용하는건 아니므로, 바로 400에러 내려주는 구조는 아닙니다.

따라서, validate해서 에러가 나오면 에러 객체를 포함해서 400을 직접 내려주는 식으로 구현하면 어느정도 될 것 같습니다.

2022-11-20 04:28 UTC, worjs commented on src/user/user.controller.ts
> +  @UseInterceptors(
별도로 빼면 좋을 것 같긴 하네요! 혹시 요 단계에서 json으로 변환까지 진행하는건 어떻게 보시나요?
아니면 거기서 더 나아가서 기본적인 type validation까지 다 해도 좋고요?

2022-11-20 04:31 UTC, woog2roid commented on src/main.ts
> +  app.useGlobalFilters(new HttpExceptionFilter());
이렇게 하면, 중간에 class(DAO)에서 new HTTPException을 던졌을 때도 Http에러를 받아줍니다.

2022-11-20 04:31 UTC, woog2roid commented on src/user/user.repository.ts
> +      .catch((err) => {
그러면 catch안에 throw new HTTPException을 추가해보면 될까요?

2022-11-20 04:33 UTC, woog2roid commented on src/user/user.repository.ts
> +    await this.prisma.user
좋은것 같습니다!

2022-11-20 04:34 UTC, woog2roid commented on src/user/user.service.ts
> +      else if (xlsxPosition === '주니어') xlsxEntrollDao.setPosition('JUNIOR');
else에 throw new Exception 던져주면 좋을 것 같네요.

2022-11-20 04:34 UTC, woog2roid commented on src/user/dao/xlsx-enroll.dao.ts
> +  public position: 'LEAD' | 'CORE' | 'MEMBER' | 'JUNIOR';
다음부턴 docs를 좀 꼼꼼히 읽어보겠습니다. ㅠㅠ

2022-11-20 04:44 UTC, woog2roid commented on src/user/user.controller.ts
> +  @UseInterceptors(
/utils/multer.option.ts 정도로 빼놓고 import해서 쓰면 될까요?
나머지 사항은 슬랙 확인 한번 부탁드리겠습니다.

2022-11-20 07:41 UTC, worjs commented on src/main.ts
> +  app.useGlobalFilters(new HttpExceptionFilter());
넵 다만 이 부분도 built-in exception 객체들을 사용해서 해결할 수 있어 보여요
https://docs.nestjs.com/exception-filters
요기에서 built-in exception 파트 보시면 될거같네요.

2022-11-20 07:44 UTC, worjs commented on src/user/user.repository.ts
> +      .catch((err) => {
그 방식도 가능한데, 사실 이렇게 되면 어떤 이유로 에러가 나온건지 알 수 없어서 500을 내려주어야 합니다.
nest에서는 에러를 처리하지 않으면 내장되어있는 global exception filter에 의해서 500이 내려갑니다.
따라서 그냥 처리하지 않아도 괜찮습니다.

2022-11-20 07:46 UTC, worjs commented on src/user/user.service.ts
> +      else if (xlsxPosition === '주니어') xlsxEntrollDao.setPosition('JUNIOR');
이부분도 엄밀히 말하면 validation부분이어서 여기보다는 constructor에 있는게(지금은 validation을 거기서 수행하고 있으니) 낫지 않을까 싶기도 하네요!

2022-11-20 07:46 UTC, worjs commented on src/user/dao/xlsx-enroll.dao.ts
> +  public position: 'LEAD' | 'CORE' | 'MEMBER' | 'JUNIOR';
아니예요ㅋㅋㅋ 그거 양 너무 많아서 여러번 봐야합니다ㅋㅋ

2022-11-20 16:39 UTC, woog2roid commented
> 1. 만약 이미 등록된 유저를 사용자가 또 등록하려고 하면 어떻게 하면 좋을까요? 기존에 있는 정보는 놔두고 나머지만 추가하는 방법도 있을거고, 그건 안된다고 409를 내려주는 방법도 있겠네요.

- prisma의 createMany에 기존에 있는 정보는 놔두고 나머지만 추가하는 옵션이 있어서 이를 사용해보려고 합니다.
- 어드민 페이지도 생길 예정이니 운영자가 거기에서 추가적인 작업을 할 수 있지 않을까 생각됩니다...

2022-11-21 03:14 UTC, woog2roid commented
다시 올렸습니다.

주요변경사항으로는,
1. class-validator를 이용한 validation 처리
2. ORM에서 createMany 적용 및 오류 처리
3. custom Exception Filter 삭제
4. controller에서 multer option 분리

2022-11-22 02:48 UTC, worjs requested changes
좋네요! 해싱같은부분은 정보 요청시에 구현하면 되는거라 나중에 해도 될거같습니다.

콘솔같은거 다 지워주세요~

2022-11-22 02:48 UTC, worjs commented on src/user/dao/xlsx-enroll.dao.ts
> +  @IsString()
IsEnum이 따로 있습니다!

2022-11-22 02:48 UTC, worjs commented on src/user/user.service.ts
> +    const xlsxEnrollDataArray: XlsxEnrollDao[] = [];
결과물이 어차피 같은 길이의 배열이라면 map을 써도 될것같네요?

2022-11-22 02:48 UTC, worjs commented on src/user/user.service.ts
> +      validateOrReject(xlsxEnrollData).catch((err) => {
이거써서 reject시의 값을 받아쓰면 type이 any로 나올겁니다.
validate 함수를 한번 보시면 좋을 것 같네요!

또, 400을 내려주는 이유 역시 error 객체에 담길건데, 그 정보를 message에 포함시켜서 요청자에게 알려주는게 좋을 것 같아요.
ex)어떤 file의 어떤 field가 잘못되었다! 이렇게 알려주면 best겠네요

2022-11-22 02:48 UTC, worjs commented on src/user/types/user-position.type.ts
> +export enum UserPosition {
별건 아닌데, type이랑 enum은 다른거니까 .enum.ts 이렇게 가도 될거같아요!

2022-11-22 02:48 UTC, worjs commented on src/user/dao/xlsx-enroll.dao.ts
> +    this.phone = '+82' + phone.substring(1);
이거 확인은 못해봤는데, 만약에 엑셀에 이걸 1112222 같은 숫자로 입력해놨으면, 여기서 잘 실행되나요?
만약 숫자면 substring함수가 string prototype함수여서 못돌릴겁니다.

2022-11-22 02:49 UTC, worjs commented
아 그리고 환경변수가 런타입에서 안들어가는거같은데, 이거 좀 확인해보고 다시 올려드릴게요.
저는 db접속이 안되네요

2022-11-22 03:41 UTC, woog2roid commented on src/user/dao/xlsx-enroll.dao.ts
> +    this.phone = '+82' + phone.substring(1);
처음부터 엑셀양식에서 010-1234-5678으로 받을거라서 상관 없을 것 같긴 합니다.

(11112222여도 String에서 돌아가지 않을까 싶긴한데...)

2022-11-22 03:41 UTC, woog2roid commented on src/user/types/user-position.type.ts
> +export enum UserPosition {
처음에 .enum.ts였는데 괜히 바꿧네요..

2022-11-22 03:45 UTC, woog2roid commented on src/user/dao/xlsx-enroll.dao.ts
> +  @IsString()
오... 그런게 있군요
그러면 enum값에 해당하는 친구들만 해주는 건가요? Enum에 한글이랑 매칭 시켜놓아서 제대로 안들어가면 undefined로 IsString에 걸리긴 하던데 밑에것들 바꾸는 김에 바꿀게요.

2022-11-22 04:34 UTC, worjs commented on src/user/dao/xlsx-enroll.dao.ts
> +    this.phone = '+82' + phone.substring(1);
엑셀에 작성할때 해당 포맷을 강제할 수 있는게 아니면 서버단에서 핸들링해야한다고 생각해요!
엑셀=>json 변환 과정에서 number로 들어올지 string으로 들어올지 잘 모르겠네요..
한번 01012345678으로 해두고 돌려보시면 될거같아요!

2022-11-23 13:28 UTC, woog2roid commented on src/user/dao/xlsx-enroll.dao.ts
> +    this.phone = '+82' + phone.substring(1);
실제로 해보니까 01012345678을 엑셀에 입력하면, 엑셀단에서 숫자로 인식이 되어서 1012345678로 바뀝니다.
그리고 엑셀에서 숫자로 넘어오기 때문에 substring이 없다고 오류가 나긴합니다.

그런데, 슬랙에 올린 엑셀 양식을 예시로 사이트에 같이 올려주면 이 부분이 문제가 되는지는 잘 모르겠습니다.
운영팀쪽에서 잘 하지 않을까 싶어서...

2022-11-23 14:05 UTC, woog2roid commented on src/user/user.service.ts
> +      validateOrReject(xlsxEnrollData).catch((err) => {
slack 확인 부탁드립니다

2022-11-27 11:08 UTC, woog2roid commented
주요변경 사항
1. phone이 number로 들어오면 오류라고 알려줍니다.
 - (010-1234-5678의 양식을 엑셀파일에서 추천하고 있으므로, 굳이 01012345678을 string으로 바꾸진 않았습니다.)
2. validateOrReject를 validate로 바꾸었으며, description등을 통해서 어떤 곳에서 양식이 틀렸는지 알려줍니다.
 - validate에 데이터 전체를 넣고 validate를 한번만 호출하려 했으나, Object안에 {data:Dao[]}의 느낌으로 들어가야 하는데, 그러면 그 자체로 코드가 조금 복잡해질 듯 하여, 여러번 호출하였습니다.
 - validate에 DAO[]를 그 자체로 넣을 수 있는 방법이 있는지 조금 찾아 보겠습니다.

그 외의 사항
1. enroll.multer.option이 export default에서 export로 바꾸었습니다. (다른 파일들도 다 이렇게 되어있길래, 양식 맞췄습니다.)

2022-11-27 14:22 UTC, worjs approved these changes
고생하셨습니다!
남은 코멘트는 거의 별거 아니여서, 수정하고 나서 돌렸을때 잘 돌아간다고 생각하시면 머지하시면 되겠습니다.

2022-11-27 14:22 UTC, worjs commented on src/user/user.service.ts
> +          return err.constraints;
요정도면 별도의 {}스코프 없이 `err => (err.constraints)`
이렇게 줘도 괜찮을 것 같습니다!

2022-11-27 14:22 UTC, worjs commented on src/user/user.service.ts
> +          Description: errorDetail,
사소하지만 camelCase로 가는게 맞을 것 같습니다!

2022-11-27 14:22 UTC, worjs commented on src/user/user.service.ts
> +    return await this.userRepository.enroll(xlsxEnrollData);
return await으로 작성하신 이유가 있나요?

2022-11-27 14:22 UTC, worjs commented on src/user/types/user-position.enum.ts
> +  '리드' = 'LAED',
오타가 있네요!

2022-11-27 14:22 UTC, worjs commented on src/user/dao/xlsx-enroll.dao.ts
> +    }
너무너무 좋습니다~~
다만 else가 굳이 필요한가 싶긴 합니다!

2022-11-27 14:22 UTC, worjs commented on src/user/user.service.ts
> +      const data = new XlsxEnrollDao(name, studentId, phone, UserPosition[xlsxPosition]);
요거 바로 return new~ 이렇게 해도 되겠군요

2022-11-27 14:22 UTC, worjs commented on src/user/user.controller.ts
> +  @Post('/xlsx')
파일 업로드 관련한 swagger 데코레이터가 있을건데, 그거까지 적용하면 좋겠군요.
기본은 postman안쓰고 swagger페이지 내에서 테스트해볼 수 있게 하는게 좋다고 생각합니다.

2022-11-30 14:51 UTC, woog2roid commented on src/user/user.service.ts
> +          Description: errorDetail,
이거 오타가 났네요!! 감사합니다

2022-11-30 14:53 UTC, woog2roid commented on src/user/user.service.ts
> +    return await this.userRepository.enroll(xlsxEnrollData);
딱히 큰 이유는 없습니다만... 습관적으로 적었습니다.

2022-11-30 14:55 UTC, woog2roid commented on src/user/types/user-position.enum.ts
> +  '리드' = 'LAED',
어... 처음에 DB를 enum없이 돌리고 그 다음에 테스트 할 때는 DB에 이미 등록된 값을 지우지 않아서 여태까지 몰랐나 봅니다. 마지막으로 풀리퀘 올릴 때는 DB 초기화하고 다 다시 해볼게요!!

2022-11-30 14:55 UTC, woog2roid commented on src/user/dao/xlsx-enroll.dao.ts
> +    }
else 없는게 훨씬 깔끔하겠네요!!

2022-11-30 14:59 UTC, woog2roid commented on src/user/user.controller.ts
> +  @Post('/xlsx')
찾아서 넣어보겠습니다!

2022-11-30 15:14 UTC, worjs commented on src/user/user.service.ts
> +    return await this.userRepository.enroll(xlsxEnrollData);
제가 찾아봤을때는 try catch로 잡을때가 아니면 return과 return await의 차이가 없는 것으로 알고 있습니다.
넣어도 좋고 안넣어도 좋다 => 저는 안넣습니다ㅋㅋ

2022-11-30 15:17 UTC, woog2roid commented on src/user/user.service.ts
> +    return await this.userRepository.enroll(xlsxEnrollData);
return this.userRepository.enroll(xlsxEnrollData);로 수정하면 될까요?

2022-11-30 15:17 UTC, worjs commented on src/user/user.service.ts
> +    return await this.userRepository.enroll(xlsxEnrollData);
넵!

2022-12-02 17:48 UTC, merged