[FEAT] 로그인 기능 구현
kugods-Homepage/kugods-server pull request #19
Opened 2022-12-28 19:08 UTC by woog2roid

## Type
PR 종류를 확인해 주세요.
- [ ] Improvement
- [x] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 어떤 목적의 작업 인가요?
로그인 기능 구현

## Why
- 어떤 이유로 작업 하셨나요?
위와 동일

## Related issue
- 관련된 Ticket을 첨부해 주세요.
#12 

## Additional context
- 추가로 알리고 싶으신 내용이 있으신가요?

1. @nest/jwt를 처음 사용해보는데, 이 부분에서 오류 있나 확인 부탁드립니다.
2. env validation이 안되어있는게 있어서 이번에 넣었습니다.
3. env는 후에 slack으로 공유하겠습니다.
4. slack을 확인해보니 refresh token은 상관쓰지 않아도 된다하여서 access token만 작업했습니다.

## Checklist
- Merge 나 Deploy 시 확인이 필요한 부분이 있다면 적어주세요.

2022-12-29 05:35 UTC, ziweek commented
코드 확인했습니다!

1.
저는 공식문서 보고 auth.module.ts에 JwtModule 넣어서 사용했었습니다.

2022-12-31 04:11 UTC, worjs requested changes
사정이 있어서 늦게 리뷰합니다..!

전체적으로 큰 문제 없어보이고, 다만 각 함수에 리턴타입 명시만 확실하게 해주시면 될 것 같네요.
고생하셨습니다.

2022-12-31 04:11 UTC, worjs commented on src/auth/auth.controller.ts
> +  async login(@Body() payload: LoginPayload) {
return 타입 명시해주세요!

2022-12-31 04:11 UTC, worjs commented on src/auth/auth.service.ts
> +    return this.jwtService.sign({
어떤 api의 리턴타입은 따로 DTO를 생성해서 하는게 더 좋다고 생각합니다.
지금은 accessToken만 내려주지만, 이후에 refresh나 별도의 정보를 추가로 내려주어야 한다고 가정합시다.
이때 서버를 먼저 배포하면 return string => return {accessToken: string, refreshToken: string}으로 api의 리턴 타입이 변경됩니다.
만약 프론트에서 이를 바로 대응하지 않으면 프론트가 배포될때 까지 login api는 사용할 수 없게 됩니다.
하위호환성이 고려되지 않은 설계라서 그런데요, 만약 처음부터 {accessToken: string}으로 내려주었다면 프론트에서 별도의 수정을 하지 않아도 refreshToken 기능을 구현여부와 상관없이 accessToken을 정상적으로 수령할 수 있게됩니다.

2022-12-31 04:11 UTC, worjs commented on src/auth/payload/login.payload.ts
> +  @IsEmail()
어차피 내부에서 해당 string으로 유저정보를 조회하는 로직이 들어가므로 굳이 email인지 여부를 validation하지는 않아도 될 것 같네요.

2022-12-31 04:11 UTC, worjs commented on src/auth/auth.service.ts
> +      throw new NotFoundException();
메세지도 같이 내려주면 판단하기 좋을 것 같습니다.

2022-12-31 04:11 UTC, worjs commented on src/auth/auth.service.ts
>      private readonly userRepository: UserRepository,
현재 저는 기존 Controller, Service 구조에서 Service에서 ORM과 DB에 관련한 세부사항들을 관리하는 Layer로 Repository를 제안했습니다. 둘을 분리한 이유는 언젠가 다른 ORM으로 변경될때 Service Layer에 있는 로직을 전혀 건드리지 않고 Repository의 코드만 변경할 수 있게 만들기 위해서입니다.

여기에 추가로 이건 개인적인 생각입니다. Repository Layer는 최대한 모듈 내의 Service에서만 참조되는게 맞다고 생각합니다. 다른 모듈이 Member 모듈을 참조를 할 때(도움을 받을 때) Member 모듈에게 ~~이런거 주세요 하면 충분하지, 그집 창고에 가서 직접 물건을 찾아올 필요는 없으니까요...(?) AuthService가 UserModule에 의존할때, 이런저런 구현사항은 UserModule에 맡겨두어야지, 직접 Repository를 참조하는 것은 좋지 않다고 생각합니다.

사실 Repository를 모듈별로 가져가는게 큰 의미가 없는 짓이긴 합니다.. TypeOrm이나 JPA의 Repository는 엔티티별로 Repository를 가지고 있으니까 명확한 편인데, prisma를 사용해버리면 어떤 곳에서든 prisma.~~~.find 해버리면 전부 조회가 가능하니까요.

그래서 일단은
1. service와 orm 로직 분리
2. 모듈간 의존시 (root)service에만 의존 => 의존관계 파악하기 쉬워짐

요정도로만 생각하고 있습니다.
이건 개인적인 의견이라 더 좋은거 있으면 언제든지 말씀해주세요..!

2022-12-31 04:19 UTC, woog2roid commented on src/auth/auth.service.ts
> +    return this.jwtService.sign({
생각해본적 없었는데 감사합니다...!!!

2022-12-31 04:24 UTC, woog2roid commented on src/auth/auth.service.ts
>      private readonly userRepository: UserRepository,
폴더/파일 구조 상 repository가 해당 도메인에 구속되는 느낌이 있는데,
다른 서비스에서 가져다 쓰는 것이 딱히 구조 상 좋아보이지는 않아서
안 그래도 이 부분 의견드리려 했습니다. 

예전에는 repository를 아예 api와 분리시켜서 가져가기도 해봤었는데,
재건님 말대로 service에만 의존할 수 있도록 하는게 조금 더 괜찮은 의견 같습니다.

userService에서 getUserAccountByEmail, joinEnrolledUser 등을 맨 밑에 만들어두면 되는 걸까요?

2022-12-31 04:29 UTC, woog2roid commented on src/auth/auth.service.ts
>      private readonly userRepository: UserRepository,
음... 아니면, repository를 아예 api들과 분리시켜서 따로 두고
service가 아닌 repository만 가져다 쓰는 건 어떨까요?

service는 비즈니스 로직이 들어가는 공간이고 repository는 DB와 관련된 공간인데,
사실 service에 단순 DB와 관련된 코드가 들어가는 것이 좋은지는 의문입니다.
(추상화 수준 면이나, 오히려 조금 더 복잡도가 높아지는 느낌이 있습니다.)

userService에서 import한 것은 generateAccessCode인데, 이건 사실 User에서 login, join까지 처리할 줄 알고 만든 메서드인데, 이것이 굳이 service에 위치해야 할 이유도 잘 모르겠습니다. /utils라던가 그런곳에 위치하여도 될 듯 하고...

2022-12-31 05:26 UTC, worjs commented on src/auth/auth.service.ts
>      private readonly userRepository: UserRepository,
> 여기에 추가로 이건 개인적인 생각입니다. Repository Layer는 최대한 모듈 내의 Service에서만 참조되는게 맞다고 생각합니다. 다른 모듈이 Member 모듈을 참조를 할 때(도움을 받을 때) Member 모듈에게 ~~이런거 주세요 하면 충분하지, 그집 창고에 가서 직접 물건을 찾아올 필요는 없으니까요...(?) AuthService가 UserModule에 의존할때, 이런저런 구현사항은 UserModule에 맡겨두어야지, 직접 Repository를 참조하는 것은 좋지 않다고 생각합니다.

이것으로 service layer 나누는 거에 대해서는 대답이 될 것 같습니다.

accesscode 생성 관련한 부분은 auth 모듈의 역할을 고려했을때 auth에 있는게 맞습니다. 그런데 그걸 auth에 두고 거기서 가져오기로(accesscode list 내려줄때) 해버리면 순환참조가 발생해서 왜그럴까 하고 생각해봤는데, accessCode를 내려주는 api가 user에 있는것 보다는 auth에 두는게 맞지 않을까 하는 생각이 드네요?

현재 db는 user와 userAccount로 나누어져 있습니다. 나누는 기준은 user에서 auth와 관련한 컬럼만 빼서 userAccount로 나눈건데요, 이런 관점에서 생각해보면 user와 상호작용할때는 user쪽의 협력을 받고, accessCode나 auth와 관련한 경우는 authRepository만들어서 처리해도 괜찮을 것 같습니다.

accessCode내려주는걸 생각해보면, auth로 위치를 옮긴 다음에 user에는 service 통해서 말그대로 미가입유저 정보만 요청하고, auth에 구현되어있는 accessCode생성 함수를 통해서 accessCode를 만들어 내리는게 역할을 확실히 분배한 것이라고 봅니다.

2022-12-31 05:50 UTC, worjs commented on src/auth/auth.service.ts
>      private readonly userRepository: UserRepository,
앞으로 어떻게 하면 좋을지는 고민이 많은데, DDD, CQRS등을 공부하다가 조금 참고한 점을 적어보자면,

1. 조회(Query)와 생성수정삭제(Command)는 생각보다 용례나 성격이 다릅니다. 
    - 생성수정삭제는 주로 자주 불러지는 것들이 정해져 있고, 한번에 그만큼만 불러와서 이것저것 작업한 뒤에 DB에 다시 반영! 이런 구조입니다. 예를 들면 Order, OrderItem 이런 관계가 있겠네요( 더 복잡할 수 있음) 이런걸 DDD에서는 Aggregate라고 부르는 듯합니다. 특징은 수정이나 따른 비즈니스로직을 수행할때 항상 묶여서 불러져온 뒤 거기 내에서 이것저것 수행하고 그대로 다시 반영하기 때문에 DB를 조회할때는 해당 쿼리가 항상 재사용가능합니다.
    - 조회의 경우에는 좀 다릅니다. 여러가지 조건에 해당하는 ~~~list를 내려주세요 하는 요청이 많은데, 성능을 위해서 필요한 컬럼만 골러서 내려주어야 하는 경우도 있고, 상황에따라 어떤 테이블과 조인할지, 맥락에 따라 매번 달라지기때문에 조회쿼리는 높은 확률로 재사용이 힘듭니다.

2. DDD에서는 비즈니스 로직을 수행할때 항상 같이 필요한(?) 단위가 있다고 하고 그것들을 묶어서 Aggregate라고 부릅니다. OrderAggregate에는 Order, OrderItem, OrderItemOption 등등이 있는 셈인데, 후자 두 테이블은 사실 Order가 없이 단독으로 사용되는 일은 드뭅니다(조회쿼리는 예외). 예를들어 주문을 한다고 하면 항상 저만큼은 불러서 처리를 하게 되겠죠. 저도 자세히는 몰라서 요정도로만 설명해두겠습니다.

그러면 우리는 어떻게 써먹으면 좋을까 해서 고민해보았습니다.
1. prisma는 조회쿼리를 치기에 너무너무 편합니다. 아무 테이블이나 잡고 join을 쭉쭉 걸기만 하면 조회가 되고, select를 통해 필요한 컬럼만 쏙쏙 가져올 수 있습니다. 조회쿼리는 어차피 재사용성도 낮기때문에 아무데서나 불러서 쓰기만 하면 됩니다. => 기존처럼 각 모듈 내 Repository에서 무지성으로 만들어씁니다.
2. 그럼 생성수정삭제쿼리는 어떻게 할까요? 이건 기존의 방식(엔티티별 Repo)에서 더 유리합니다. 생성,수정,삭제의 단위가 되는 단위를 엔티티로 만들어서 묶어놓고, Factory라는 layer를 만들어서 이를 분리해볼 수 있을 것 같습니다. 그러면 기존 방식처럼 특정 조건으로 엔티티를 조회하고 싶다 하면 Factory에 요청을 하면 조회한 뒤에 엔티티 객체를 생성해서 내려줍니다. 이것저것 service에서 처리를 하거나 엔티티에 작성된 함수로 처리하고 나서, 저장하거나 삭제하고 싶으면 다시 Factory에게 그걸 넘겨주면 반영합니다.
Factory에서 prisma를 주입받아서 관련 처리를 다 해주어도 좋고, 아니면 factory가 repository를 주입받아서 db관련 처리는 싹다 다시 repo에게 위임해도 되겠습니다.

2022-12-31 08:30 UTC, woog2roid commented on src/auth/auth.service.ts
>      private readonly userRepository: UserRepository,
코멘트 확인해서 다시 작업후에 풀리퀘 올리도록 하겠습니다.

2022-12-31 17:44 UTC, woog2roid commented on src/auth/auth.service.ts
>      private readonly userRepository: UserRepository,
1. Command와 Query를 다른 Layer로 분리하여 복잡도를 줄이는 것이 CQRS 패턴(1단계) 맞나요? 상당히 동의하는 바이고, repository에서 무지성으로 만들어쓰다는 것이 처음엔 조금 거부감이 들었으나, 크게 겹칠 일도 없는 쿼리들이고, 크게 어려운 작업도 아니니 제때 테스트만 된다면 괜찮을 것 같습니다.

2. 다만, repo와 factory는 설명이 조금 이해가 되지 않습니다. 
> "특정 조건으로 엔티티를 조회하고 싶다 하면 Factory에 요청을 하면 조회한 뒤에 엔티티 객체를 생성해서 내려줍니다. 이것저것 service에서 처리를 하거나 엔티티에 작성된 함수로 처리하고 나서, 저장하거나 삭제하고 싶으면 다시 Factory에게 그걸 넘겨주면 반영합니다."

Factory에 쿼리를 보내고, Factory에 커맨드도 보낸다는 건가요? 레이어가 분리된 모습이 아니지 않나요?

3. auth와 user 도메인 관련해서, 의미론적으로는 현재 user에 적혀있는 것들을 모두 auth로 옮겨야 할 것 같은데, 어떻게 생각하시나요?

4. Service Layer를 나누는 것에 대한 고민을 해보았는데,
> "accessCode내려주는걸 생각해보면, auth로 위치를 옮긴 다음에 user에는 service 통해서 말그대로 미가입유저 정보만 요청하고, auth에 구현되어있는 accessCode생성 함수를 통해서 accessCode를 만들어 내리는게 역할을 확실히 분배한 것이라고 봅니다."

이 부분에서 미가입유저 정보는 무지성 생성된 auth repo를 통해 바로 받는다고 하면 딱히 user Service를 받을 필요가 없습니다.

그리고 하나의 service가 또 다른 service를 호출하는 것이 바람직한 지도 의문이고요.

layer를 나누는 것이 1)추후에 orm을 변경하는 등의 리팩토링이 있을 때 편하게 하기 위해, 2) 인수인계 등을 위한 클린한 코드 아키텍쳐 유지의 목적이라면,

1)은 repository만 수정하면 그만이고, 2)는 전에 말씀드린 대로 repo를 단순 호출하는 service의 method가 클린한 지 잘 모르겠습니다.

2023-01-01 09:00 UTC, worjs commented on src/auth/auth.service.ts
>      private readonly userRepository: UserRepository,
1. Layer라고 해야하나.. 음 맞는 것 같기도 한데 정확히는 다루는 방식이 다르다고 보면 되겠습니다. 저는 Command와 Query는 "재사용 가능성"에 있어서 가장 큰 차이가 있다고 보고, Query는 어차피 재사용이 어려우니 재사용하려고 애쓰지말고, Command는 재사용할 여지가 많으니 최대한 객체로 잘 모델링해서 그 객체 단위로 불러와서 쓰고 저장하는 식으로 사용해보자는 의미입니다. 어떻게보면 기존 방식이랑 유사하겠네요!
2. 요건 저도 명확하게 사용해본 부분은 아닌데, 제가 생각해본 factory는 Command를 객체로 모델링해서 사용한다고 가정했을때 이 객체들의 생성, 수정, 삭제에 관련한 로직을 처리하는 클래스입니다. 관련한 로직이라 함은, 생성,수정의 경우는 DB에 있는 unique constraint 체크라던가, 삭제의 경우에는 삭제 가능 여부 체크, 다른 같이 삭제해주어야 하는(cascade) 경우는 같이 삭제해준다거나 하는 로직들이 있습니다. 관련한 처리를 하고 객체들을 생성해서 요청자에게 돌려줍니다.
간단한 예시를 들어보겠습니다. 예를들어, 어떤 학생이 특정 강의에 수강신청하는 요청을 보냈습니다. 그럼 다음과 같은 것들을 검증해야합니다.
    1. 강의의 신청 정원이 남아있는가?
   2. 학생이 여유학점이 있는가?
   3. 학과제한, 학년제한에 걸리지 않는가?
   4. 이미 본인이 신청한 강의인가?
   
   요청시에는 학생의 ID와 신청하고자하는 강의의 ID정보를 서버로 보낼 것입니다. 이 요청을 처리하기 위해서는, 크게 두 가지의 
Aggregate이 필요하게 됩니다. 하나는 학생, 하나는 강의입니다. 학생 aggregate은 학생 자신의 정보(전공, 학년 등)와 자신이 이미 신청한 강의 list(몇 학점 신청했는지, 이미 신청한 강의인지 체크하기 위함)를 불러와야 합니다. 강의 aggregate은 강의 하나만 있으면 되겠네요.

    그러면 다음과 같은 엔티티가 필요합니다. Student class, Lecture class, SignedLecture class입니다. 여기서 Student는 SignedLecture[]를 필드로 가지고 있고, Lecture는 따로 관련된 것이 없습니다.

    Service는 factory에 ID로 student를 요청합니다. factory는 바로 repository에 id를 기반으로 학생 정보와, 신청한 과목리스트를 불러오고, 불러온 데이터를 Student class 생성시에 생성자로 넘겨주면, student class의 생성자 함수에서 같은 방식으로 SignedLecture를 생성합니다. 즉, 한번에 필요한 데이터를 repo에 요청해 가져온 뒤, student aggregate의 root가 되는 student class를 생성하면서 이 데이터를 전부 넘겨줍니다. 그러면 student 생성자에서 받은 데이터를 기반으로 연결된 다른 클래스들도 쭉 생성해서 한번에 student aggregate를 생성하는 방식입니다. 그렇게 생성된 aggregate를 service에 돌려줍니다.

    이렇게 불러온 student aggregate와 lecture aggregate를 가지고 비즈니스 로직을 수행합니다. 1,3은 lecture class에 구현해둔 public method, 2,4는 student class에 구현해둔 public method를 통해 처리할 수 있습니다. 처리한 이후, 다시 factory의 update함수에 student aggregate를 인자로 넘겨주면, 필요한 체크를 수행한 뒤에 repo에 aggregate를 넘겨주고 반영합니다.

    정리하자면,
service가 factory에 aggregate 생성 요청 => factory는 특정 조건으로 aggregate에 필요한 정보를 repo에 요청하여 DB 조회 => 가져온 값으로 aggregate 생성하여 service에 리턴 => service에서 비즈니스 로직 처리 후 저장이 필요한 경우 factory에 다시 저장 요청 => factory에서 필요한 체크 후 repo에 저장 요청 => repo가 받아서 저장.

3. 동의합니다! accessCode가 들어간 로직만 옮겨도 될것 같기는 합니다만,, 뭔가 xlsx업로드와 list내려주기가 세트인 것 같아서 별도의 api로 나누어져있으면 보는 입장에선 조금 곤란할수도 있을 것 같아요
4. 어느정도 맞는 말인 것 같아요. 굳이 모듈간 의존관계를 만들 필요가 있을까 싶기도 하고.. 한번 안하는쪽으로 해볼까요? 아 그래도 accessCode를 유틸로빼자는건 반대합니다. 날짜변환하는 함수처럼 완전 global하게 쓰이는게 명확한 함수면 그렇게 하는데, 저정도면 auth에서 private method로 관리하는게 맞다고 생각해요.
5. 오 완전 그거예여 factory라는건 결국 어떻게보면 db의 table을 aggregate이라는 도메인 모델 그룹으로 매핑하는걸 도와주는 클래스라는 느낌입니다. 단순히 함수 하나인데도 layer나누는거는 그냥 역할의 관점입니다. service, factory, repository를 팀 단위에서 나름의 역할 컨벤션을 정해놓고 layer를 나눠두면, 어떤 경우에는 factory에서 수행할게 없을수도 있죠. 하지만 그렇다고 비슷한 동작을 수행하는데 어떤건 로직이 간단해서 repo를 직접치고, 어떤건 factory를 통해서 치면 코드를 파악할때 조금 번거로움이 있지 않을까요? 근데 이런건 말그대로 팀 컨벤션의 문제여서 그거대로 정하면 됩니다ㅋㅋ

2023-01-01 09:03 UTC, worjs approved these changes
확실히 service 메소드 4개나 생긴거보면 auth repo로 하면 안되나? 생각이 들긴 하겠네요!
어느정도 그부분에 동의하고 최대한 모듈간 의존은 안하는쪽으로 풀어보는거로 합시당

하나만 고치고 바로 가시죠!

2023-01-01 09:03 UTC, worjs commented on src/auth/dto/login.dto.ts
> +  accessToken: string;
요거 느낌표만 추가해주세요ㅋㅋ

2023-01-01 09:57 UTC, merged