Feat/4
kugods-Homepage/kugods-server pull request #5
Opened 2022-11-15 05:49 UTC by alrbs10

## Type
PR 종류를 확인해 주세요.
- [ ] Improvement
- [X] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
유저 테이블을 모델링하였습니다. 기본적인 정보(미리 입력해놓을) user table과, 로그인/회원가입할 때 필요한 부분인 user account table로 구성되어 있습니다.

## Related issue
- resolve #4 

## Additional context
- 

## Checklist
-

2022-11-15 06:28 UTC, worjs requested changes
여기까지 작성하느라 고생하셨습니다! 피드백 확인해주시고, 수정해서 다시 노티해주시면 확인하겠습니다. DB는 한번 잘만들어두어야 앞으로 편해서 최대한 꼼꼼히 확인하고 지나갈게요!

추가로 제안드리고 싶은 부분은,
1. created_at, updated_at과 같은 컬럼은 만들어두면 우리끼리 테스트하기도 편하고, 이래저래 앞으로 편해지는 부분이 있어서 모든 테이블에 넣는 편입니다. 관련 구문들을 prisma가 지원하고 있으니 확인해보시고 추가해주시면 좋을 것 같아요!
2. prisma format이라는 명령어를 치면 schema파일에서 문법적인 오류를 잡아주고 예쁘게 포맷해줍니다.

2022-11-15 06:28 UTC, worjs commented on prisma/schema.prisma
> +  accessCode String @unique
accessCode는 슬랙 쓰레드에서도 이야기가 약간 오고갔었는데, 구조상 DB에 저장할 필요는 없어보입니다!

2022-11-15 06:28 UTC, worjs commented on prisma/schema.prisma
> +model User_Account{
모델명은 여기서는 PascalCase로 통일할게요!
테이블같은 경우에는 @@map(user_account)같은 구문을 넣어두면 table이름은 snake_case로 넣을 수 있습니다!

2022-11-15 06:28 UTC, worjs commented on prisma/schema.prisma
> +  student_id Int @unique
마찬가지로 column명도 camelCase로 통일하고 @map('studend_id')를 붙여주면 db에는 저렇게 들어갑니다.

2022-11-15 06:28 UTC, worjs commented on prisma/schema.prisma
> +  level String?
level이 혹시 lead, core, admin 등등의 권한 개념일까요?
만약 그렇다면 세 가지 고려할만한 부분이 있는데,
1. 권한 개념이라면 사용자의 권한을 확인하는 용도로 쓰일 것으로 보이는데 user_account 테이블에 위치하는 것이 좋아보입니다.
2. 권한에 들어갈만한 항목이 크게 많지 않아보여서 enum을 고려해보는건 어떨까요?
3. 권한이 없는 경우는 없을 수 없으니 not null로 하고, default 값을 지정해도 좋을 것 같습니다.

2022-11-15 06:28 UTC, worjs commented on prisma/schema.prisma
> +  id    Int    @id  @default(autoincrement())
개인적으로, user 테이블의 pk는 정수보다는 uuid형태의 고유한 string으로 사용하는 편인데요, 그 이유는 아래와 같습니다.

62라는 id로 특정 유저의 정보를 조회하는 api요청을 누군가 확인한다면, 
1. 사용자는 1~61로 다른 유저의 정보를 조회할 수 있다는 사실을 할 수 있습니다.
2. 우리가 최소 62명 이상이라는 정보를 알 수 있습니다.

1번같은 경우에는 우리가 인증, 인가를 제대로 구현해두면 쉽게 털리지는 않겠지만, 그래도 유저의 개인정보 정도는 충분히 적용할만한 가치가 있는 것 같아서 제안드립니다. prisma에서도 자동으로 uuid를 생성해서 집어넣는 함수를 지원하고 있습니다.

2022-11-15 06:28 UTC, worjs commented on prisma/schema.prisma
> +  phone String? @unique
phone같은 경우에는 우리가 그걸로 유저를 식별할게 아니라면 unique를 걸지 않아도 괜찮아 보이고, kugods가입자라면 전화번호는 모두 받을 것 같아서 굳이 nullable하지 않아도 될 것 같네요!

2022-11-16 12:38 UTC, alrbs10 commented
수정하였습니다! 확인부탁드려요

2022-11-16 15:06 UTC, worjs requested changes
거의 다 된 것 같네요! 말씀드린 것 정도만 수정해주시면 될 것 같아요. 수고하셨습니다!

2022-11-16 15:06 UTC, worjs commented on prisma/schema.prisma
> +enum Position {
1. User라는 맥락에서만 사용되니까 UserPosition 어떨까요!
2. 얘도 @@map 지원됩니당
3. enum 아이템들은 뭔가 풀 대문자 쓰는게 국룰이라고 생각하는데 어떠신가요ㅋㅋㅋ

2022-11-16 15:06 UTC, worjs commented on prisma/schema.prisma
> +  isAdmin   Boolean? @map("is_admin")
is_admin은 무조건 있는거라고 보고, default를 false로 주면 될거같아요!

2022-11-16 15:06 UTC, worjs commented on prisma/schema.prisma
> +  uuid      String   @unique
요건 user_id로 가실까요? user table 참조하는 fk라서 그게 더 명확할 것 같네요.

2022-11-16 15:06 UTC, worjs commented on prisma/schema.prisma
> +  position  Position
이 정보는 관리자가 입력하는 시점에 결정되는 정보 같아서, 저는 user table에 속하는게 적절해 보입니다.

2022-11-16 15:15 UTC, alrbs10 commented on prisma/schema.prisma
> +enum Position {
풀대문자 동의합니다 ㅋㅋㅋ 수정해놓겠습니다!

2022-11-16 15:21 UTC, alrbs10 commented
반영 완료하였습니다! 확인 후 머지하면 될 것 같습니다

2022-11-16 15:25 UTC, worjs approved these changes

2022-11-17 12:41 UTC, worjs approved these changes
고생하셨습니다! 가시죠~
* 머지할때 네이밍만 [Schema] or [DB] ~~~ 형태로 하면 좋을 것 같아요!

2022-11-17 14:02 UTC, merged